### PR TITLE
Activity response update - heart_rate example

### PR DESCRIPTION
**Pull request by ItachiEU**
Adding heart_rate to the example response from activity: https://docs.tryvital.io/api-reference/activity/get-summary

### CODE REVIEW

**Review by gabrieleangeletti — APPROVED** [review]
How come Garmin? Because Oura doesn't have all the fields?

**Comment by RuiAAPeres** [comment]
But we do have timeseries HR data for Oura available. Can't we calculate this?

**Comment by ItachiEU** [comment]
> But we do have timeseries HR data for Oura available. Can't we calculate this?

Quite possibly. If I am not mistaken @andersio has selected withings, garmin and fitbit first, because the data was easily available in the activity summary. The other ones might require more effort and would probably require some planning.

**Review by andersio — APPROVED** [review]

**Comment by andersio** [comment]
(moved discussion to slack)

**Pull request merged**
