### PR TITLE
[VIT-3353] Add trigger on custom event; to be sent from mono

### PR DESCRIPTION
**Pull request by piresrui**
Adds a trigger on a custom event. This event will be sent from mono repo on release to trigger the swagger json pull

### CODE REVIEW

**Comment by andersio** [comment]
:0

**Comment by andersio** [comment]
you can do cross repo events??!??!?!?!?

**Review by andersio — APPROVED** [review]

**Comment by piresrui** [comment]
> you can do cross repo events??!??!?!?!?

Yeah apparently, it's a little sneaky tho

**Review by gabrieleangeletti — APPROVED** [review]
#magic

**Pull request merged**
